// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCarousel: typeof import('element-ui/lib/carousel')['default']
    ElCarouselItem: typeof import('element-ui/lib/carousel-item')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IMdiAccountReactivate: typeof import('~icons/mdi/account-reactivate')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
